### ISSUE TITLE
Customized pinpoint breaks the send button

### ISSUE THREAD

**Issue by 20015jjw** [Lickability/PinpointKit#150]
Hi there. I'm trying to customize the pinpointkit to replace the default sender, then tapping on the send button didn't call the sendFeedback method in my customized sender. 

Then I discovered that initializing a pinpointkit object by just calling `PinpointKit()` would do the same thing, breaking the send button. 

Basically, 
```
let pinpointKit = PinpointKit()
pinpointKit.show(fromViewController: viewController)
```
will break the send button, so that nothing happens when I tap on it

while
```
let pinpointKit2 = PinpointKit.defaultPinpointKit
pinpointKit2.show(fromViewController: viewController)
```
won't.

According to your code, `defaultPinpointKit` is initialized by `PinpointKit()`, and it was never modified anywhere. So I'm not sure what's causing this error. 

Thank you in advance.

**Comment by mliberatore** [comment]
Hi, @20015jjw! Thanks for trying out PinpointKit. 

I believe your issue is that nothing is holding a strong reference to the `PinpointKit` instance you’re creating, and therefore the `feedbackDelegate` is `nil`’d out (note: `feedbackDelegate`, which is `weak`, is set to `self` in `PinpointKit`’s initializer.) To confirm this, set a breakpoint in `sendButtonTapped()`, and confirm that  `feedbackDelegate` is actually `nil` at this point when you tap "Send". If that’s the case, this is why the "Send" action isn’t reported back to you via delegation.

The reason  using `defaultPinpointKit` works is because it’s a `static let`, and therefore a strong reference is held to it throughout the duration of the app’s life. To fix your issue, you should declare your `pinpointKit` constant somewhere else, such that a strong reference is kept. For example, if the `class` or `struct` you’re calling `pinpointKit.show(fromViewController: viewController)` from is around for the duration of PinpointKit’s use, declare it as a `class` or `struct`-level constant, instead of a property declared within the method from which you’re calling `show(fromViewController:)`.

Please re-open if this doesn’t solve your issue.

**Comment by 20015jjw** [comment]
@mliberatore It worked. Thank you so much :D

**Comment by mliberatore** [comment]
You’re welcome, @20015jjw 🎉
