### ISSUE TITLE
Doesn't compile in Swift 3

### ISSUE THREAD

**Issue by iandundas** [Lickability/PinpointKit#194]
(Code needs migrating)

**Comment by mliberatore** [comment]
Hey @iandunas! Thanks for checking out PinpointKit. While we prep for our 1.0 release, our migrated Swift 3 work is currently available on the `develop` branch, so you’ll need to follow the instructions on `develop`’s README rather than `master`’s. This will allow you to use PinpointKit in your Swift 3 branch and the latest versions of Xcode. [Here’s a link](https://github.com/Lickability/PinpointKit/tree/develop#cocoapods).

Please let me know if that works for you!

**Comment by iandundas** [comment]
Smexcellent :) 🙏🏼

**Comment by mliberatore** [comment]
Closing this issue as "resolved". @iandundas, if you still have any issues compiling, please let us know!

**Comment by iandundas** [comment]
Excellent! Thanks
