### ISSUE TITLE
Can't Install w Cocoapods

### ISSUE THREAD

**Issue by rauls4** [Lickability/PinpointKit#209]
#[!] Unable to satisfy the following requirements:

- `PinpointKit (~> 1.0)` required by `Podfile`

Using - 'PinpointKit' only installs v. 0.9 which does not appear to be Swfit3 compatible.

I updated the repo, still no luck.

**Comment by mliberatore** [comment]
Hi, @rauls4. Sorry for the mishap. You caught us right in between [merging our 1.0 release work](https://github.com/Lickability/PinpointKit/pull/203) and actually [releasing the 1.0 version](https://github.com/Lickability/PinpointKit/releases/tag/1.0.0).

Since 1.0 has now been released, you can run `pod repo update` and try installing 1.0 again. Please let me know if this solves your problem.

Thanks for checking out PinpointKit!
