### ISSUE TITLE
Consider Detailed Steps for PinpointKit Customization

### ISSUE THREAD

**Issue by mliberatore** [Lickability/PinpointKit#216]
See [this comment](https://github.com/Lickability/PinpointKit/issues/212#issuecomment-278464190) wherein I describe how one could provide a custom `LogCollector` implementation.

Consider whether we should have more detailed instructions like this (or examples) for how one could customize PinpointKit. Our current README has a [Customization](https://github.com/Lickability/PinpointKit#customization) section, but it’s possible that more detailed information could help users get started.

**Comment by leisurehound** [comment]
+1.  I've been able to look at the various init methods to get the gist of customization (and indeed see the results of color changes, title changes, etc. but I also get a run time SIGABT because likely I have not set something up fully.

`Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <DriverMonitor.SettingsMenuTableViewController 0x103805e60> for the key path "contentSize" from <UITableView 0x107007c00> because it is not registered as an observer.'`

I imagine that PinpointKit is registering the observer so its something in my customization settings that is incomplete.  I do not get that error when I simply init PinpointKit with a list of email addresses to send to.

**Comment by iadcialim** [comment]
No updates on this huh?
