### ISSUE TITLE
If default Mail app is uninstalled, send is greyed out - need a warning/alert

### ISSUE THREAD

**Issue by ghost** [Lickability/PinpointKit#263]
## Expected Behavior
Send may be greyed out but users will have no clue as to how to proceed. adding an alert to say "Mail app not found - please install from appstore" or something will help.

## Steps to Reproduce the Problem

  1. delete Mail app from device.
  2. run pinpointkit UI. 
  3. click send from screenshot.
  4. email composer has send button greyed out.

## Specifications

  - Version:
  - Platform:

**Comment by mliberatore** [comment]
Hi @ghubaddole, thanks for filing an issue.

When I follow the steps to reproduce the problem in your issue using the included Example app, I see the alert in the screenshot below. That is, I cannot make it to the mail composer because we detect that mail sending isn’t possible, and display the alert [here in the `SenderDelegate` implementation](https://github.com/Lickability/PinpointKit/blob/e4e45703259bb556f5c9da79409972ebe7de0f8e/PinpointKit/PinpointKit/Sources/Core/PinpointKit.swift#L97-L106).

Since you’re experiencing different behavior, could you provide additional information to help us debug the issue?

* What iOS version are you using, and on which version of PinpointKit?
* If you have a breakpoint in the function linked above, does that breakpoint get hit when you tap the Send button to show the mail composer?
* Could you post a snippet of how you‘re initializing `PinpointKit`, or perhaps post a sample project in which the issue occurs?

Thank you!

![IMG_8CA8CC336CF2-1](https://user-images.githubusercontent.com/7883805/59939386-c7e6c000-9425-11e9-8f4d-aa666fa42759.jpeg)

**Comment by mliberatore** [comment]
Hey, @ghubaddole. I just wanted to check in on this. Is this issue still affecting you? We’d love to help out if the alert behavior is not working appropriately.
